{
    'name': 'SAP Monitoring Dashboard (Mockup)',
    'version': '0.1',
    'summary': 'Mockup frontend dashboard built with OWL + Chart.js (Grafana style)',
    'category': 'Tools',
    'author': 'Generated by ChatGPT',
    'license': 'LGPL-3',
    'depends': ['web'],
    'data': [
        'views/dashboard_action.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sap_monitoring/static/src/js/dashboard_action.js',
            'sap_monitoring/static/src/js/charts.js',
            'sap_monitoring/static/src/js/mock_data.js',
            'sap_monitoring/static/src/xml/dashboard_template.xml',
            'sap_monitoring/static/src/scss/dashboard_styles.scss',
            "sap_monitoring/static/lib/chartjs/chart.min.js",
        ],
    },
    'installable': True,
    'application': False,
}
